# Generated by Django 5.0.14 on 2026-09-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='equipos/'),
        ),
    ]
